version: '2'
services:
  neo4j:
    image: neo4j:3.0.7
    network_mode: host
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/password
      - dbms.memory.heap.initial_size=1024
      -	dbms.memory.heap.max_size=1024
    cap_add:
      - SYS_RESOURCE
    ports:
      - "7474:7474"
      - "7687:7687"
      - "1337:1337"
    volumes:
      - ./neo4j/plugins:/plugins
      - ./neo4j/data:/data
      - ./neo4j/import:/var/lib/neo4j/import
